### ISSUE TITLE
Does it support trainning in different languages?

### ISSUE THREAD

**Issue by kadirnar** [Respaired/Tsukasa-Speech#6]
Hi, I'm training the StyleTTS2 model from scratch. I really like the innovations brought by the Tsukasa-Speech library. I want to prepare an English model using the https://huggingface.co/datasets/shb777/gemini-flash-2.0-speech dataset. What should I do for this?

Do you recommend this library for phoneme processing?
https://github.com/ShoukanLabs/VoPho

**Comment by kadirnar** [comment]
I tried training yesterday but got errors. Also, could you share the config file for the first stage?

https://huggingface.co/Respair/Tsukasa_Speech/blob/main/Configs/config.yml

**Comment by Respaired** [comment]
Salute.

You shouldn't use the pre-trained text aligner (Utils/ASR) in this repo to train on anything other than japanese. but you can simply swap it with the one in the original STTS2 repo for English. (otherwise, please train your own.)

yeah VoPho is solid. 

The config file for the first stage and second stage is the same. I have provided (almost) everything I used to train Tsukasa in this repo. I recommend you to use HuggingFace's repository for the latest changes. I usually don't update my github repos. maybe that'll fix the errors? I don't know what error you faced but this repository is tested across many datasets, hardware and languages.

**Comment by kadirnar** [comment]
@Respaired Didn't you use whisper in the first training? 

<img width="687" alt="Image" src="https://github.com/user-attachments/assets/520e2cdd-572b-43b7-b56a-cbd793ef6b94" />

I will download it again from the HuggingFace platform. I will change the ASR model and try training with English again. I'm training the StyleTTS2 model with 8xH100. However, I'm getting a GPU memory error at epoch 50.

**Comment by Respaired** [comment]
I didn't use the single-speaker config. Tsukasa was trained on [config_kanade.yml](https://huggingface.co/Respair/Tsukasa_Speech/blob/main/Configs/config_kanade.yml)

**Comment by kadirnar** [comment]
> I didn't use the single-speaker config. Tsukasa was trained on [config_kanade.yml](https://huggingface.co/Respair/Tsukasa_Speech/blob/main/Configs/config_kanade.yml)

I don't understand. Didn't you do the firs stage training? How did you train this model?
<img width="997" alt="Image" src="https://github.com/user-attachments/assets/fa39dd27-1140-4544-97ce-cf12f2c38d2c" />

I'm training the StyleTTS2 model from scratch using 8xH100. I set the batch size to 16. However, I'm getting a GPU memory error after the 50th epoch. Do you have any idea how I can solve this?

**Comment by Respaired** [comment]
I used the config I gave you the link. both stages must be trained, so yes I trained that.

try pip install accelerate==0.* and see if it helps.

**Comment by kadirnar** [comment]
> I used the config I gave you the link. both stages must be trained, so yes I trained that.
> 
> try pip install accelerate==0.* and see if it helps.


If you used this config file for stage 1 and 2, shouldn't pretrained_model be None? Because you're training from scratch. Isn't this config file for finetuning? Because you're providing the model file obtained from the second training as the path?

I'll set accelerate.0 and share the results tomorrow, thank you ❤

**Comment by Respaired** [comment]
i didn't train the model in one session. i constantly pause and resume. so yeah, you should remove that line. set it to pretrained_model = "" unless you want to resume from one of your own checkpoints.

**Comment by kadirnar** [comment]
> i didn't train the model in one session. i constantly pause and resume. so yeah, you should remove that line. set it to pretrained_model = "" unless you want to resume from one of your own checkpoints.

Yesterday, I tried training the StyleTTS2 model by adding bfloat16, but the loss values started returning nan. I want to use your repo. However, are these models specific to the Japanese language?

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/e0ead253-5085-4448-9342-2854033fb2e8" />

Should I change these codes for English?

<img width="1008" alt="Image" src="https://github.com/user-attachments/assets/08ee206c-3896-476e-ade2-ec4e891adf5f" />

**Comment by kadirnar** [comment]
I am interested in receiving paid consulting services from you. Could you please provide your contact information?

**Comment by Respaired** [comment]
> > i didn't train the model in one session. i constantly pause and resume. so yeah, you should remove that line. set it to pretrained_model = "" unless you want to resume from one of your own checkpoints.
> 
> Yesterday, I tried training the StyleTTS2 model by adding bfloat16, but the loss values started returning nan. I want to use your repo. However, are these models specific to the Japanese language?
> <img alt="Image" width="617" src="https://private-user-images.githubusercontent.com/36204372/421322250-e0ead253-5085-4448-9342-2854033fb2e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE3MDcyMTcsIm5iZiI6MTc0MTcwNjkxNywicGF0aCI6Ii8zNjIwNDM3Mi80MjEzMjIyNTAtZTBlYWQyNTMtNTA4NS00NDQ4LTkzNDItMjg1NDAzM2ZiMmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzExVDE1MjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZDMyMDVjYzQwMDY2YzkzMmYxNjAzYmYwNDczZGQ0MDU2M2I4ZTYyNWVmYzFjNDJjYWFmNDdjZDFmOGZlOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K6v4LS3lIIJEs7AcymFVCujCDu6X4kg4b12gtAWWRgE">
> 
> Should I change these codes for English?
> <img alt="Image" width="1008" src="https://private-user-images.githubusercontent.com/36204372/421323106-08ee206c-3896-476e-ade2-ec4e891adf5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE3MDcyMTcsIm5iZiI6MTc0MTcwNjkxNywicGF0aCI6Ii8zNjIwNDM3Mi80MjEzMjMxMDYtMDhlZTIwNmMtMzg5Ni00NzZlLWFkZTItZWM0ZTg5MWFkZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzExVDE1MjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhY2RlMzU5OWQwOGI4NGQ2MTAwMDczYmE2NjFmNzkzMGI5OWU2YzU2MjUzNjk2ZjA4MTE3ZDQwMDdjYzM0MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IJHqVQFz1zl1_C4aQNFfPlWXdOMb41Uuoz0J74CrpsI">

Those are the Phonemization scripts for Japanese and the Kotodama sampling method. none of them are required for training the base model. Remove the KTD models from the build_model function in the models.py 

As for the STTS2, you may want to visit it's repository and ask your issues related to STTS over there. I can only help you with Tsukasa here.


If you are new to Speech processing, I recommend you to start with a simpler model like VITS or E2TTS that are simple and can be trained fully e2e.

STTS and its variants (like Tsukasa) are complex networks not suitable for beginners imo, you have to do many preparations to achieve the best result possible.

**Comment by kadirnar** [comment]
Thank you very much for your help. I downloaded the codes and models from the HuggingFace platform. I changed the ASR model. I converted the data to .csv format. I'm preparing the config file but I have some questions.

Configs/config_kanade.yml:
```
epochs_1st: 30 # number of epochs for first stage training (pre-training)
epochs_2nd: 20 # number of peochs for second stage training (joint training)

loss_params:
diff_epoch: 4 # style diffusion starting epoch (2nd stage)
joint_epoch: 999 # joint training starting epoch (2nd stage)
```
You mentioned that you continuously updated the epoch values. 

- How many epochs in total did you train for the first stage and second stage? 
- Should I change the diff_epoch and joint_epoch values? Isn't the value of 4 too small?

**Comment by kadirnar** [comment]
I deleted audio files longer than 8 seconds. However, I'm still getting this error.
```
Epoch [1/200], Step [10/561], Mel Loss: 1.17536, Gen Loss: 0.00000, Disc Loss: 0.00000, Mono Loss: 0.00000, S2S Loss: 0.00000, SLM Loss: 0.00000
Time elasped: 14.092263221740723
Epoch [1/200], Step [20/561], Mel Loss: 0.82955, Gen Loss: 0.00000, Disc Loss: 0.00000, Mono Loss: 0.00000, S2S Loss: 0.00000, SLM Loss: 0.00000
Time elasped: 23.106489419937134
Epoch [1/200], Step [30/561], Mel Loss: 0.77619, Gen Loss: 0.00000, Disc Loss: 0.00000, Mono Loss: 0.00000, S2S Loss: 0.00000, SLM Loss: 0.00000
Time elasped: 31.43715786933899
....
[rank2]:   File "/mnt/kadirnar/Tsukasa_Speech/.venv/lib/python3.10/site-packages/xlstm/blocks/mlstm/backends.py", line 65, in parallel_stabilized_simple
[rank2]:     log_fg_matrix = torch.where(ltr, _log_fg_matrix[:, :, 1:, 1:], -float("inf"))  # (B, NH, S, S)
[rank2]: RuntimeError: The size of tensor a (512) must match the size of tensor b (635) at non-singleton dimension 3
```

Dataset:
![Image](https://github.com/user-attachments/assets/e9c14eb8-2768-4983-b237-d70823e1b39c)

Config.yml:
```

log_dir: "Models/Style_English_v00"
first_stage_path: ""
save_freq: 1
log_interval: 10
device: "cuda"
epochs_1st: 200 # number of epochs for first stage training (pre-training)
epochs_2nd: 100 # number of peochs for second stage training (joint training)
batch_size: 64
max_len: 800 # maximum number of frames
pretrained_model: ""
second_stage_load_pretrained: false # set to true if the pre-trained model is for 2nd stage
load_only_params: true # set to true if do not want to load epoch numbers and optimizer parameters

F0_path: "Utils/JDC/bst.t7"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/epoch_00080.pth"

PLBERT_dir: 'Utils/PLBERT/'

data_params:
  train_data: "Data/train_list.csv"
  val_data: "Data/val_list.csv"
  root_path: "hf_data"
  OOD_data: "Data/OOD_LargeScale_.csv"
  min_length: 50 # sample until texts with this size are obtained for OOD texts

preprocess_params:
  ...
model_params:
  multispeaker: true
...
    type: 'istftnet' # either hifigan or istftnet
    ...
  # speech language model config
  slm:
      model: 'Respair/Whisper_Large_v2_Encoder_Block' # The model itself is hardcoded, change it through -> losses.py
...

  # style diffusion model config
  diffusion:
...
    # diffusion distribution config
...
loss_params:
..
    diff_epoch: 20 # style diffusion starting epoch (2nd stage)
    joint_epoch: 50 # joint training starting epoch (2nd stage)
optimizer_params:
...
slmadv_params:
...
```
